workflows:
  default-workflow:
    name: TikTok App Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get flutter packages
        working_directory: tiktok_app
        script: |
          flutter packages get
      - name: Build APK
        working_directory: tiktok_app
        script: |
          flutter build apk --release
    artifacts:
      - tiktok_app/build/app/outputs/flutter-apk/*.apk
